### ISSUE TITLE
lock in dev fails

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-api#24]
In timereport-dev whenever you try to lock you will always get back

```
timereport_backend - ERROR - Caught exception for <function create_lock at 0x7f46c3773400>
Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1104, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 265, in create_lock
db_v1.create_lock(app.current_request.json_body)
AttributeError: module 'chalicelib.lib.db_v1' has no attribute 'create_lock'
```
There is obviously something wrong.

This blocks https://github.com/codelabsab/timereport-slack/issues/116

**Comment by kamigerami** [comment]
fixed already in https://github.com/codelabsab/timereport-api/commit/cdf37ec5176bb250ebd48158b0389c9988b26fe3
